# YAML parameters file for plane detection algorithm
ground_clearance:
  min_height: 0.25 # Ground clearance minimum in meters
  max_height: 1.6 # ground clearance maximum in meters

blob_properties:
  x_dimension: 0.1  # The horizontal width of the individual subsection we want
  y_dimension: 0.1  # The vertical height of the individual subsection we want
  min_surface_area: 0.01 # The minimum surface area of the complete polygon we are interested in
  max_surface_area: 5.5 # The maximum surface area of the complete polygon we are interested in

plane_segment:
  xy_resolution: 0.05 # Nearest neighbor cluster growing resolution in xy plane for plane detection
  z_resolution: 0.02 # Nearest neighbor cluster growing resolution in z axis for plane detection
  norm_threshold: 0.2 # in radians

pointcloud:
  base_frame: "map"
  topic_name: "/oil/perception/head_camera/triggered_cloud"  # Topic that hope listens to for cloud data. This is the topic trigger.py publishes to
  camera_source_topic_name: "/oil/perception/head_camera/sync_filtered_cloud" # Topic onto which cloud filtered data from the camera is published to 

viz: false